version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd!
      - MSSQL_PID=Evaluation
      - MSSQL_MEMORY_LIMIT_MB=4096
    ports:
      - "1433:1433"
    hostname: sqlpreview
    container_name: sqlpreview
    cap_add:
      - SYS_PTRACE
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P P@ssw0rd! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s